apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - mongo/statefulset.yaml
  - mongo/service.yaml
  - redis/deployment.yaml
  - redis/service.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - backend/hpa.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - worker/deployment.yaml
  - worker/hpa.yaml
  - ingress.yaml

images:
  - name: yourdockerhubusername/ai-task-platform-backend
    newName: ai-task-platform-backend
    newTag: latest
  - name: yourdockerhubusername/ai-task-platform-frontend
    newName: ai-task-platform-frontend
    newTag: latest
  - name: yourdockerhubusername/ai-task-platform-worker
    newName: ai-task-platform-worker
    newTag: latest
